#!/usr/bin/env python3
"""Analyze assets/song.mp3 and write src/data/audio.js.

Produces the beat grid (tempo + first-beat offset) and a few audio envelopes
sampled at 60 Hz that drive the audio-reactive parts of the animation:

  kick   - low-band (<150 Hz) onset envelope with a fast attack / smooth decay
  energy - overall loudness (smoothed RMS)
  vocal  - rough vocal-band energy from a REPET-SIM foreground separation
  hat    - high-band (>6 kHz) onset envelope

Everything is precomputed so the animation is a pure function of time and can be
rendered frame-by-frame deterministically.

Requires: numpy, librosa, soundfile, ffmpeg on PATH.
Usage:    python3 tools/analyze_audio.py
"""
import json
import os
import subprocess
import tempfile

import librosa
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SONG = os.path.join(ROOT, "assets", "song.mp3")
OUT = os.path.join(ROOT, "src", "data", "audio.js")
FPS = 60
SR = 22050
HOP = 256


def load():
    with tempfile.TemporaryDirectory() as d:
        wav = os.path.join(d, "song.wav")
        subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", SONG, "-ac", "1",
                        "-ar", str(SR), wav], check=True)
        y, _ = librosa.load(wav, sr=SR)
    return y


def envelope(x, attack=0.5, release=0.12, fps=FPS):
    """One-pole follower: fast attack, exponential release (release in seconds)."""
    out = np.zeros_like(x)
    rel = np.exp(-1.0 / (release * fps))
    v = 0.0
    for i, s in enumerate(x):
        v = v + (s - v) * attack if s > v else v * rel
        out[i] = v
    return out


def norm(x, pct=98):
    hi = np.percentile(x, pct)
    return np.clip(x / (hi + 1e-9), 0, 1)


def resample(times, values, grid):
    return np.interp(grid, times, values)


def main():
    y = load()
    duration = len(y) / SR

    # ---- beat grid (straight line fit through tracked beats) ----
    oenv = librosa.onset.onset_strength(y=y, sr=SR, hop_length=HOP)
    _, beats = librosa.beat.beat_track(onset_envelope=oenv, sr=SR, hop_length=HOP,
                                       units="time", start_bpm=114, tightness=400)
    idx = np.arange(len(beats))
    period, offset = np.polyfit(idx, beats, 1)

    S = np.abs(librosa.stft(y, hop_length=HOP))
    freqs = librosa.fft_frequencies(sr=SR)
    t = librosa.times_like(S[0], sr=SR, hop_length=HOP)
    grid = np.arange(0, duration, 1.0 / FPS)

    # ---- kick: low band spectral flux ----
    low = S[freqs < 150].sum(axis=0)
    flux = np.maximum(0, np.diff(low, prepend=low[0]))
    kick = envelope(norm(resample(t, flux, grid), 97), attack=0.9, release=0.16)

    # ---- hats: high band spectral flux ----
    high = S[freqs > 6000].sum(axis=0)
    hflux = np.maximum(0, np.diff(high, prepend=high[0]))
    hat = envelope(norm(resample(t, hflux, grid), 97), attack=0.9, release=0.08)

    # ---- energy: smoothed RMS ----
    rms = librosa.feature.rms(y=y, hop_length=HOP)[0]
    energy = norm(resample(t, rms, grid), 99)
    k = int(FPS * 0.25)
    energy = np.convolve(energy, np.ones(k) / k, mode="same")

    # ---- vocal: REPET-SIM foreground in the voice band ----
    S_filter = librosa.decompose.nn_filter(S, aggregate=np.median, metric="cosine",
                                           width=int(librosa.time_to_frames(2, sr=SR, hop_length=HOP)))
    S_filter = np.minimum(S, S_filter)
    mask_v = librosa.util.softmask(S - S_filter, 10 * S_filter, power=2)
    band = (freqs > 250) & (freqs < 4000)
    ve = (mask_v * S)[band].sum(axis=0)
    vocal = envelope(norm(resample(t, ve, grid), 98), attack=0.6, release=0.1)

    q = lambda a: [int(round(v * 99)) for v in np.clip(a, 0, 1)]
    data = {
        "duration": round(duration, 3),
        "bpm": round(60.0 / period, 4),
        "beat": round(float(period), 6),
        "offset": round(float(offset), 4),
        "fps": FPS,
        "kick": q(kick),
        "hat": q(hat),
        "energy": q(energy),
        "vocal": q(vocal),
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Generated by tools/analyze_audio.py - do not edit by hand.\n")
        f.write("// Envelopes are 0..99 integers sampled at `fps` Hz.\n")
        f.write("export const AUDIO = " + json.dumps(data, separators=(",", ":")) + ";\n")
    print(f"duration {duration:.2f}s  bpm {60/period:.2f}  offset {offset:.3f}s  -> {OUT}")


if __name__ == "__main__":
    main()
